name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main # Chạy workflow khi push lên nhánh main
  workflow_dispatch: # Cho phép chạy thủ công

# Phân quyền ghi để push lên nhánh gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng: lấy toàn bộ lịch sử commit để last updated hiển thị đúng

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Deploy
        run: |
          cd vi
          mkdocs gh-deploy --config-file mkdocs.yml --force
